### ISSUE TITLE
is an upgrade to TYPO3 8 LTS planned ?

### ISSUE THREAD

**Issue by Lobster1956** [fabarea/metadata#19]
for using with TYPO3 8 LTS - what is to do ???

**Comment by fabarea** [comment]
Not much I assume. Just changing the compatibility to CMS 8.x in ext_emconf.php and we could be good to go. I don't have a TYPO3 8 at hand unfortunately... If you could test it and give your feedback if that works for you like that I could do the release. 
All the best!

**Comment by fnagel** [comment]
It seems the indexing is broken in TYPO3 8.7, see https://github.com/fabarea/metadata/pull/21/commits/eaa7f5afa0230b3905f39f20519e03c44f294d12

**Comment by sgrossberndt** [comment]
I am testing metadata 2.3.0-dev on a TYPO3 8.7 installation with PostgreSQL. It works so far :-)

**Comment by tiemsche** [comment]
I tried the latest  2.3.0-dev-Branch in TYPO3 v8 and the File list is broken. The error message is "The class "Fab\Metadata\Index\ImageMetadataExtractor" you are registering is not available". What is the current development status? We are currently upgrading a website to TYPO3 v8 and have a lot of features that rely on metadata. Will there be any compatible version soon? Let me know if there are any current problems we might help with.

**Comment by fabarea** [comment]
Autoload problem? The class is well here:
https://github.com/fabarea/metadata/blob/master/Classes/Index/ImageMetadataExtractor.php

Perhaps, we should add an autoload section in 

https://github.com/fabarea/metadata/blob/master/ext_emconf.php

Could you test? The same as we do in composer.json

**Comment by fabarea** [comment]
Just released tag 2.3.0 which is tagged compatible TYPO3 v8
