### ISSUE TITLE
Workaround for access-label no longer works

### ISSUE THREAD

**Issue by sgrossberndt** [fabarea/metadata#22]
As apparently when the TCA from Overrides/* is cached the constant `TYPO3_version` is not available the workaround to display the "Access" label no longer works. As it seems to have worked with older versions maybe we should just reverse the condition.

https://github.com/fabarea/metadata/blob/1b18b63db61f89c3bddfb8b2c2d88b254b1b4ecb/Configuration/TCA/Overrides/sys_file_metadata.php#L195

**Comment by bnf** [comment]
That code looks correct and it works for me in a v8 installation.
TCA Caching from `Configuration/TCA` and `Configuration/TCA/Overrides` is performed on the resulting `$GLOBALS['TCA']` array. Therefore there is no problem with cached or uncached version. Also `TYPO3_version` is available whenever TCA is loadeded – cached or uncached.

**Comment by sgrossberndt** [comment]
Issue can be closed as support for TYPO3 < 8.7 has been dropped-
