### ISSUE TITLE
Compatibility for TYPO3 CMS 9.5

### ISSUE THREAD

**Issue by jokumer** [fabarea/metadata#29]
Version 2.4.0-dev is not compatible with current TYPO3 CMS 9.5, which should be to support upgrade.

If you install current version in TYPO3 CMS version 9.5.5, then
* extension configuration check uses deprecated TYPO3_CONF_VARS key
* extension configuration breaks by class loading from extension configuration user-function which renders result for PHP extension check (exif & iptc)
* extension configuration will not render with new introduced css classes for success/warning

I will add a pull request, which solves these issue..

**Comment by sgrossberndt** [comment]
A version with compatibility to TYPO3 9.5 has not been released yet, are you going to do that in the near future? :-)

**Comment by jokumer** [comment]
Release for TYPO3 9.5 accepted from my side. Version 2.4.0-dev is running fine.
