### ISSUE TITLE
missing categories in tca for filetype image

### ISSUE THREAD

**Issue by manuelLink** [fabarea/metadata#3]
by overwriting $tca['types'] for the filetype image the configuration for showing the categories ("--div--;LLL:EXT:lang/locallang_tca.xlf:sys_category.tabs.category, categories,") gets removed.
This results in being unable to edit categories for images in the backend.

**Comment by fabarea** [comment]
Do you have a suggestion / solution to fix the problem?

**Comment by jmverges** [comment]
You are also loosing Access tab Label at least in 7.3 >

**Comment by fabarea** [comment]
Ah damned!

Isn't it a matter of dependency and precedence to EXT:filemetadata? What happen with:

```
'depends' =>
    array (
      'cms' => '',
      'typo3' => '6.2.0-7.99.99',
      'filemetadata' => '',  <--- new line
    ),
```

update: to be added in ext_emconf.php

**Comment by jmverges** [comment]
is not related with that dependency.
