### ISSUE TITLE
IPTC source should be saved in metadata source field

### ISSUE THREAD

**Issue by mueller-sebastian** [fabarea/metadata#31]
Instead of 
	'2#115' => 'publisher',

should it not be
        '2#115' => 'source',

Otherwise IPTC source metadata is saved in publisher instead of source.
Or is this on purpose? I'm not that deep into metadata stuff....

**Comment by sgrossberndt** [comment]
Line in question is

https://github.com/fabarea/metadata/blob/master/Classes/Index/ImageMetadataExtractor.php#L60

According to 
https://www.iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#source

`'2#115'` is indeed `source`, not `publisher`. Both fields are defined in `EXT:filemetadata`:

https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/filemetadata/ext_tables.sql#L12
