### ISSUE TITLE
TCA of field credit should only allow 32 chars

### ISSUE THREAD

**Issue by mueller-sebastian** [fabarea/metadata#32]
TCA allows 255 characters, DB field is VARCHAR(32) and therefore removes content.

I'm not sure why this was set to 32.
https://www.iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#credit-line

**Comment by mueller-sebastian** [comment]
OK, found the why 32 chars here https://www.iptc.org/std/IIM/4.1/specification/IIMV4.1.pdf:

2:110 Credit Not repeatable, maximum of 32 octets, consisting of graphic
characters plus spaces.
Identifies the provider of the objectdata, not necessarily the
owner/creator.

PHP (getimagesize) returned only 32 chars in my tests here.

So the may the TCA max length should be changed or some info provided.

**Comment by fabarea** [comment]
Could you provide with a PR, please?

**Comment by sgrossberndt** [comment]
Issue can be closed as PR was merged.
