### ISSUE TITLE
Compatibility with TYPO3 9

### ISSUE THREAD

**Issue by Nostrabramus** [fabarea/metadata#34]
Hello,

looking on TER I found this extension where it is defined that supported up to TYPO3 8.
On GitHub, however, it would seem to also support TYPO3 9.
Are you developing and it hasn't been released yet?
Do you already have the expected time for the possible release?

Thanks for your attention.

regards
Abramo

**Comment by fabarea** [comment]
Thanks for the reminder. I just released on the TER 3.0.0 which is compatible with v8 and v9 of TYPO3
