### ISSUE TITLE
Wrong "GPS Coordinate" parsing if value isn't present

### ISSUE THREAD

**Issue by rbinder** [fabarea/metadata#38]
I got some troubles with inserting GPS coordinates when lattitude/longitude aren't present in metadata...

Following change in **function parseGpsCoordinate** worked for me:
`return ($value === null || $value === '' || $value == 0) ? '0.00000000000000' : (string)$value;`

instead of:
`return $value === null ? null : (string)$value;`

Best regards,
Roman

**Comment by fabarea** [comment]
Could you provide with a PR?

**Comment by sgrossberndt** [comment]
Fixed by https://github.com/fabarea/metadata/pull/43, can be closed.
