### ISSUE TITLE
Check values before operate with arithmethic division on processing EXIF data

### ISSUE THREAD

**Issue by jokumer** [fabarea/metadata#7]
Avoid scheduler task of FAL metadata extract to fail to execute successfully, regarding type and value of incoming EXIF data. In some cases, existing EXIF data could contain zero values (such as resolution/fraction, shutter speed or GPS coordinates).
3 commits submited as pull-requests.

**Comment by sgrossberndt** [comment]
Fixed by https://github.com/fabarea/metadata/pull/6, can be closed.
