### ISSUE TITLE
TYPO3 7.4 support

### ISSUE THREAD

**Issue by fnagel** [fabarea/metadata#8]
In TYPO3 7.4.0 the tasks fails with an error message:

```
Serialization of 'Closure' is not allowed
```

**Comment by fabarea** [comment]
Damned! Hopefully nothing too serious...

**Comment by fnagel** [comment]
False alarm. 

Seems my error was caused by a missing file -- needed to fix this and voilá: everything works fine. Extraction of exif data works as expected.

Seems metadata is TYPO3 7.4 ready :-D
